const CARD_ACTIONS = {
  ADD_CARD: 'ADD_CARD',
  UPDATE_CARD: 'UPDATE_CARD',
  DELETE_CARD: 'DELETE_CARD',
  ADD_CARD_LIST: 'ADD_CARD_LIST',
  SET_CARD_LIST_MODE: 'SET_CARD_LIST_MODE',
  EMPTY_CARD_LIST: 'EMPTY_CARD_LIST',
  ADD_CARD_LIST_LENGTH: 'ADD_CARD_LIST_LENGTH',
  PREVENT_SCROLL: 'PREVENT_SCROLL',
};

export { CARD_ACTIONS };
